// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.1
// source: controller.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Controller_Ping_FullMethodName             = "/Controller/ping"
	Controller_RegisterAgent_FullMethodName    = "/Controller/registerAgent"
	Controller_UnregisterAgent_FullMethodName  = "/Controller/unregisterAgent"
	Controller_ListenTask_FullMethodName       = "/Controller/listenTask"
	Controller_NotifyTaskResult_FullMethodName = "/Controller/notifyTaskResult"
	Controller_StreamTaskLog_FullMethodName    = "/Controller/streamTaskLog"
	Controller_StreamEvent_FullMethodName      = "/Controller/streamEvent"
)

// ControllerClient is the client API for Controller service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ControllerClient interface {
	Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	RegisterAgent(ctx context.Context, in *AgentId, opts ...grpc.CallOption) (*Empty, error)
	UnregisterAgent(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error)
	ListenTask(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Task], error)
	NotifyTaskResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*Empty, error)
	StreamTaskLog(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Log, Empty], error)
	StreamEvent(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Event, Empty], error)
}

type controllerClient struct {
	cc grpc.ClientConnInterface
}

func NewControllerClient(cc grpc.ClientConnInterface) ControllerClient {
	return &controllerClient{cc}
}

func (c *controllerClient) Ping(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Controller_Ping_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) RegisterAgent(ctx context.Context, in *AgentId, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Controller_RegisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) UnregisterAgent(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Controller_UnregisterAgent_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) ListenTask(ctx context.Context, in *Empty, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Task], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Controller_ServiceDesc.Streams[0], Controller_ListenTask_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Empty, Task]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Controller_ListenTaskClient = grpc.ServerStreamingClient[Task]

func (c *controllerClient) NotifyTaskResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, Controller_NotifyTaskResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *controllerClient) StreamTaskLog(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Log, Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Controller_ServiceDesc.Streams[1], Controller_StreamTaskLog_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Log, Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Controller_StreamTaskLogClient = grpc.ClientStreamingClient[Log, Empty]

func (c *controllerClient) StreamEvent(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[Event, Empty], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Controller_ServiceDesc.Streams[2], Controller_StreamEvent_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[Event, Empty]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Controller_StreamEventClient = grpc.ClientStreamingClient[Event, Empty]

// ControllerServer is the server API for Controller service.
// All implementations must embed UnimplementedControllerServer
// for forward compatibility.
type ControllerServer interface {
	Ping(context.Context, *Empty) (*Empty, error)
	RegisterAgent(context.Context, *AgentId) (*Empty, error)
	UnregisterAgent(context.Context, *Empty) (*Empty, error)
	ListenTask(*Empty, grpc.ServerStreamingServer[Task]) error
	NotifyTaskResult(context.Context, *TaskResult) (*Empty, error)
	StreamTaskLog(grpc.ClientStreamingServer[Log, Empty]) error
	StreamEvent(grpc.ClientStreamingServer[Event, Empty]) error
	mustEmbedUnimplementedControllerServer()
}

// UnimplementedControllerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedControllerServer struct{}

func (UnimplementedControllerServer) Ping(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedControllerServer) RegisterAgent(context.Context, *AgentId) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterAgent not implemented")
}
func (UnimplementedControllerServer) UnregisterAgent(context.Context, *Empty) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UnregisterAgent not implemented")
}
func (UnimplementedControllerServer) ListenTask(*Empty, grpc.ServerStreamingServer[Task]) error {
	return status.Errorf(codes.Unimplemented, "method ListenTask not implemented")
}
func (UnimplementedControllerServer) NotifyTaskResult(context.Context, *TaskResult) (*Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NotifyTaskResult not implemented")
}
func (UnimplementedControllerServer) StreamTaskLog(grpc.ClientStreamingServer[Log, Empty]) error {
	return status.Errorf(codes.Unimplemented, "method StreamTaskLog not implemented")
}
func (UnimplementedControllerServer) StreamEvent(grpc.ClientStreamingServer[Event, Empty]) error {
	return status.Errorf(codes.Unimplemented, "method StreamEvent not implemented")
}
func (UnimplementedControllerServer) mustEmbedUnimplementedControllerServer() {}
func (UnimplementedControllerServer) testEmbeddedByValue()                    {}

// UnsafeControllerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ControllerServer will
// result in compilation errors.
type UnsafeControllerServer interface {
	mustEmbedUnimplementedControllerServer()
}

func RegisterControllerServer(s grpc.ServiceRegistrar, srv ControllerServer) {
	// If the following call pancis, it indicates UnimplementedControllerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Controller_ServiceDesc, srv)
}

func _Controller_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).Ping(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_RegisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AgentId)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).RegisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_RegisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).RegisterAgent(ctx, req.(*AgentId))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_UnregisterAgent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).UnregisterAgent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_UnregisterAgent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).UnregisterAgent(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_ListenTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(Empty)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ControllerServer).ListenTask(m, &grpc.GenericServerStream[Empty, Task]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Controller_ListenTaskServer = grpc.ServerStreamingServer[Task]

func _Controller_NotifyTaskResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ControllerServer).NotifyTaskResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Controller_NotifyTaskResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ControllerServer).NotifyTaskResult(ctx, req.(*TaskResult))
	}
	return interceptor(ctx, in, info, handler)
}

func _Controller_StreamTaskLog_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControllerServer).StreamTaskLog(&grpc.GenericServerStream[Log, Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Controller_StreamTaskLogServer = grpc.ClientStreamingServer[Log, Empty]

func _Controller_StreamEvent_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ControllerServer).StreamEvent(&grpc.GenericServerStream[Event, Empty]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Controller_StreamEventServer = grpc.ClientStreamingServer[Event, Empty]

// Controller_ServiceDesc is the grpc.ServiceDesc for Controller service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Controller_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Controller",
	HandlerType: (*ControllerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ping",
			Handler:    _Controller_Ping_Handler,
		},
		{
			MethodName: "registerAgent",
			Handler:    _Controller_RegisterAgent_Handler,
		},
		{
			MethodName: "unregisterAgent",
			Handler:    _Controller_UnregisterAgent_Handler,
		},
		{
			MethodName: "notifyTaskResult",
			Handler:    _Controller_NotifyTaskResult_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "listenTask",
			Handler:       _Controller_ListenTask_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "streamTaskLog",
			Handler:       _Controller_StreamTaskLog_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "streamEvent",
			Handler:       _Controller_StreamEvent_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "controller.proto",
}
